### PR TITLE
stix_import improved

### PR DESCRIPTION
**Pull request by davidonzo**
Added basic suppor for:

- file_name
- file_size
- Email attachments

I hope it will be used almost as a snippet code.
Hope this help and many thanks to share your knowledge (and your software of course).

### CODE REVIEW

**Comment by Rafiot** [comment]
First of all, can you squash it in one single commit? :) 

Besides that, it looks good to me. @FloatingGhost can you check it out?

**Comment by FloatingGhost** [comment]
I was half considering just closing the request based on those commit messages, but I won't go full Torvalds on you.

I'll check it out tomorrow <3

**Comment by davidonzo** [comment]
Sorry for the confusion I created.
I close this request for a new one with a single commit.

**Comment by Rafiot** [comment]
No problem ;)

**Pull request closed without merging**
