### PR TITLE
Stiximport refactored 2

### PR DESCRIPTION
**Pull request by davidonzo**
Main changes:
The code has been refactored defining a dedicated function for the following objects:

- File objects: buildFileAttribute
- Address objects: buildAddressAttribute
- Email objects: buildEmailMessageAttribute
- Domain object: buildDomainNameAttribute
- Hostname object: buildHostnameAttribute
- URI object: buildURIAttribute

I think some function definition can be compacted in a single function, but I thing this way should be better to code management's purpose.

All objects listed below now support the "Related_Objects" import, but just for the first level.

Minor changes:

- Added support for SHA512 hash
- Added support for file_extension using the attribute type "pattern-in-file" because MISP seems to not have a specific object

Applied @FloatingGhost changes requested (I hope by the right way)

Thanks for your time in advance and for your support in code review.

### CODE REVIEW

**Comment by FloatingGhost** [comment]
See [this](https://landscape.io/github/MISP/MISP-STIX-Converter/pulls/14) - you've mixed tabs and spaces, and there are some indentation issues

**Comment by davidonzo** [comment]
Solved: [35ab32b](https://github.com/davidonzo/MISP-STIX-Converter/commit/35ab32b6d248d646a8610ded82074e534d1f70ba)

**Comment by FloatingGhost** [comment]
thanks <3

**Comment by davidonzo** [comment]
Thanks to you!

**Pull request merged**
